# pip install openai openai-agents

"""Demo 1c: tool use with a schema generated by @function_tool.

See 01c_function_calling_agents_sdk.md for the full explanation.
"""

import json
import os

from agents import function_tool
from openai import OpenAI

client = OpenAI()
model = os.getenv("OPENAI_MODEL", "gpt-5.6")


def count_letter(word: str, letter: str) -> int:
    """The real function behind the tool. The model never runs this itself."""
    return word.lower().count(letter.lower())


# @function_tool reads the name, description, and JSON schema straight off
# the function above -- same information 1a hand-typed and 1b built from a
# Pydantic model, generated here from a type-hinted signature and docstring.
count_letter_tool = function_tool(count_letter)

tools = [
    {
        "type": "function",
        "name": count_letter_tool.name,
        "description": count_letter_tool.description,
        "parameters": count_letter_tool.params_json_schema,
    }
]

question = "How many times does the letter 'r' appear in 'strawberry'?"
response = client.responses.create(
    model=model,
    input=question,
    tools=tools,
    tool_choice="required",
)

call = response.output[0]
args = json.loads(call.arguments)
print(f"Model asked to call: {call.name}({args})")

result = count_letter(**args)
print(f"Real function returned: {result}")

follow_up = client.responses.create(
    model=model,
    previous_response_id=response.id,
    input=[
        {
            "type": "function_call_output",
            "call_id": call.call_id,
            "output": str(result),
        }
    ],
)
print(f"Assistant: {follow_up.output_text}")
